name: ukrse2022_mlops_data_prep
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.8
  - dask-labextension
  - distributed
  - holoviz
  - imbalanced-learn
  - intake
  - ipykernel
  - iris=3.1
  - jupyterlab
  - mlflow=1.20
  - pandas=1.3
  - pip
  - scikit-learn=0.24
  - tensorflow=2.8
  - tensorboard=2.8
  - xarray=0.19
  - pip:
    - ray
    - ray[serve]
    - ray[tune]
 
